# Generated by Django 3.0.5 on 2022-12-08 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topping',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
        ),
    ]
